# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:android)

cwd = Dir.pwd

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(task: "clean")

    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => "#{cwd}/../app/partyq_release.jks",
        "android.injected.signing.store.password" => ENV["PARTYQ_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["PARTYQ_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["PARTYQ_KEY_PASSWORD"]
      }
    )
  end

  desc "Build Android App Bundle"
  lane :build_bundle do
    gradle(task: "clean")

    gradle(
      task: "bundle",
      build_type: "Release",
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => "#{cwd}/../app/partyq_release.jks",
        "android.injected.signing.store.password" => ENV["PARTYQ_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["PARTYQ_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["PARTYQ_KEY_PASSWORD"]
      }
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    build

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      groups: "group-one",
      release_notes: "Lots of amazing new features to test out!"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    build_bundle

    upload_to_play_store
  end
end
